### ISSUE TITLE
What are your plans with this project?

### ISSUE THREAD

**Issue by max-ri** [DallasC/Freshlime#1]
Hello!
Just found this fork of my project.
I was wondering what your plans are for this. What features do you have that I would be missing? What do you plan on adding?
Wouldn't it been easier to just ask me for any alterations you wanted? Or help putting them into my addon? If you only want your own guide in its own addon there would have been a very easy way to do so.
You know I will still be doing lots of improvements to my addon. It will be quite challenging for you to integrate everything I have here, don't you think?  
Cheers, Borick

**Comment by DallasC** [comment]
Yeah you're right I'm going to close this repo. Didn't really think it through and definitely shouldn't have made the repo public as it was just for personal use.
